Fix iOS build error in FluStudy_us (#620)
When I try to build the iOS app, I get the following error:

```
/Users/mathewsb/a/audere/FluStudy_us/ios/fluathome/RDTReader/ImageProcessor.mm:76:1: error: reference to 'Ptr' is ambiguous
Ptr<BRISK> detector;
^
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/fluathome/RDTReader/ImageProcessor.mm:9:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/fluathome/RDTReader/ImageProcessor.h:9:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVFoundation.h:14:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/AVFoundation.framework/Headers/AVAnimation.h:11:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:43:
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CFBase.h:77:
/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS13.4.sdk/usr/include/MacTypes.h:248:41: note: candidate found by name lookup is 'Ptr'
typedef char *                          Ptr;
                                        ^
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/fluathome/RDTReader/ImageProcessor.mm:9:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/fluathome/RDTReader/ImageProcessor.h:12:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/Pods/libopencv-contrib-audere-3.4.6-xcode10.1/opencv2.framework/Headers/imgcodecs/ios.h:48:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/Pods/libopencv-contrib-audere-3.4.6-xcode10.1/opencv2.framework/Headers/core/core.hpp:48:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/Pods/libopencv-contrib-audere-3.4.6-xcode10.1/opencv2.framework/Headers/core.hpp:54:
In file included from /Users/mathewsb/a/audere/FluStudy_us/ios/Pods/libopencv-contrib-audere-3.4.6-xcode10.1/opencv2.framework/Headers/core/base.hpp:58:
/Users/mathewsb/a/audere/FluStudy_us/ios/Pods/libopencv-contrib-audere-3.4.6-xcode10.1/opencv2.framework/Headers/core/cvstd.hpp:261:8: note: candidate found by name lookup is 'cv::Ptr'
struct Ptr
       ^
```

I'm not entirely sure why this would fail for me, when it must have worked
for others in the past.  Has something changed in the iOS SDK?  (As you can
see from the error message, I'm building with the 13.4 SDK.)

In any case, the fix seems fairly straightforward... what do you think?